### ISSUE TITLE
comments app.js

### ISSUE THREAD

**Issue by csnktms** [NWilde4/yawmee#1]
https://github.com/NWilde4/yawmee/blob/ccab5dec4fdad18e2c73f2c56752f51bce8fa960/client/src/App.js#L15
what about using `empty string` (`''`) as a default starting value to be `"type"` consistent. we know for sure that the token is of type `object String`.

https://github.com/NWilde4/yawmee/blob/ccab5dec4fdad18e2c73f2c56752f51bce8fa960/client/src/App.js#L19
what about checking not only the existence but for the length? `"   "` is considered to be a `truthy` value.

```js
token?.trim()?.length > 0

// but this works fine as well:
token?.trim()?.length
```

https://github.com/NWilde4/yawmee/blob/ccab5dec4fdad18e2c73f2c56752f51bce8fa960/client/src/App.js#L24
same applies here:

```js
if(!token?.trim()?.length) {
...
}
```

**Comment by normanwilde** [comment]
Thanks, valid points, updated accordingly

**Comment by normanwilde** [comment]
Thanks, valid points, updated accordingly
