### ISSUE TITLE
comments index.js

### ISSUE THREAD

**Issue by csnktms** [NWilde4/yawmee#2]
https://github.com/NWilde4/yawmee/blob/ccab5dec4fdad18e2c73f2c56752f51bce8fa960/client/src/index.js#L17

it is a general convention to use `Bearer` with a capital `B`

https://github.com/NWilde4/yawmee/blob/ccab5dec4fdad18e2c73f2c56752f51bce8fa960/client/src/index.js#L3

for the sake of good order, let's first import all the modules which is residing inside `node_modules` so called `absolute` imports, so the order should be like this:

```js
import React from 'react'
import ReactDOM from 'react-dom'
import { ChakraProvider } from "@chakra-ui/react"
import '@fontsource/m-plus-2'
import { 
  ApolloClient, ApolloProvider, HttpLink, InMemoryCache 
} from '@apollo/client' 
import { setContext } from '@apollo/client/link/context'
// i prefer to separate the absolute imports from the relative ones with a new line as well
import App from './App'
import theme from './theme'

```

**Comment by normanwilde** [comment]
Thanks, this has been updated accordingly.
